steps:
  general:
    verbose: true
  githubPublishRelease:
    addClosedIssues: true
    addDeltaToLastRelease: true
    excludeLabels:
      - 'discussion'
      - 'duplicate'
      - 'invalid'
      - 'question'
      - 'wontfix'
      - 'stale'
    owner: 'virendersinghrana'
    repository: 'jenkins-library'
    releaseBodyHeader: ''
  githubCreatePullRequest:
    base: master
    owner: 'virendersinghrana'
    repository: 'jenkins-library'
    labels:
      - 'REVIEW'
      - 'go-piper'
    assignees:
      - 'marcusholl'
      - 'daniel-kurzynski'
      - 'fwilhe'
      - 'CCFenner'
      - 'OliverNocon'
      - 'nevskrem'
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'CF'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: 'mckdvsd'
      space: 'mckdevapp'
